/Users/vladimirkopylov/bots/venv/lib/python3.9/site-packages/urllib3/__init__.py:35: NotOpenSSLWarning: urllib3 v2 only supports OpenSSL 1.1.1+, currently the 'ssl' module is compiled with 'LibreSSL 2.8.3'. See: https://github.com/urllib3/urllib3/issues/3020
  warnings.warn(
Traceback (most recent call last):
  File "/Users/vladimirkopylov/bots/panictab_bot/panictab_bot.py", line 6, in <module>
    bot.send_message(CHAT_ID, "panictab_bot работает ✅")
  File "/Users/vladimirkopylov/bots/venv/lib/python3.9/site-packages/telebot/__init__.py", line 1549, in send_message
    apihelper.send_message(
  File "/Users/vladimirkopylov/bots/venv/lib/python3.9/site-packages/telebot/apihelper.py", line 264, in send_message
    return _make_request(token, method_url, params=payload, method='post')
  File "/Users/vladimirkopylov/bots/venv/lib/python3.9/site-packages/telebot/apihelper.py", line 162, in _make_request
    json_result = _check_result(method_name, result)
  File "/Users/vladimirkopylov/bots/venv/lib/python3.9/site-packages/telebot/apihelper.py", line 189, in _check_result
    raise ApiTelegramException(method_name, result, result_json)
telebot.apihelper.ApiTelegramException: A request to the Telegram API was unsuccessful. Error code: 404. Description: Not Found
