Traceback (most recent call last):
  File "/Users/vladimirkopylov/bots/panic_bot/panic_bot.py", line 1, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
Traceback (most recent call last):
  File "/Users/vladimirkopylov/bots/panic_bot/panic_bot.py", line 1, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
Traceback (most recent call last):
  File "/Users/vladimirkopylov/bots/panic_bot/panic_bot.py", line 1, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
Traceback (most recent call last):
  File "/Users/vladimirkopylov/bots/panic_bot/panic_bot.py", line 1, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
Traceback (most recent call last):
  File "/Users/vladimirkopylov/bots/panic_bot/panic_bot.py", line 1, in <module>
    import telebot
ModuleNotFoundError: No module named 'telebot'
